mysite_project/blog/urls.py
from django.urls import path
from . import views


app_name = "blog"
urlpatterns = [
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("", views.IndexView.as_view(), name="post_list"),
]

mysite_project/milage/urls.py
from django.urls import path, include
from .routers import router
from . import views


app_name = "milage"
urlpatterns = [
    path("api/", include(router.urls), name="api_router"),
    path("class-based/", views.ClassBasedView.as_view(), name="class_based_drf"),
    path(
        "class-based-detail/<int:pk>",
        views.ClassBasedDetailView.as_view(),
        name="class_detail",
    ),
    path("", views.BaseView.as_view(), name="index"),
]

mysite_project/milage/models.py
from django.db import models


class FuelEffeciency(models.Model):
    miles_driven = models.DecimalField(decimal_places=2, max_digits=6)
    gallons_used = models.DecimalField(decimal_places=3, max_digits=6)
    date_measured = models.DateField()
    date_recorded = models.DateField(auto_now_add=True)
    owner = models.ForeignKey(
        "auth.User", related_name="fuelefficiency", on_delete=models.CASCADE
    )

mysite_project/milage/views.py
from django.views.generic import TemplateView
from rest_framework import viewsets, generics
from rest_framework import permissions
from rest_framework.renderers import JSONRenderer, AdminRenderer
from rest_framework_xml.renderers import XMLRenderer

from .models import FuelEffeciency
from .serializers import FuelEffeciencySerializer


class FuelEffeciencyViewSet(viewsets.ModelViewSet):
    serializer_class = FuelEffeciencySerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)
    renderer_classes = (AdminRenderer, XMLRenderer, JSONRenderer)

    def get_queryset(self):
        return FuelEffeciency.objects.all()

    def perform_create(self, serializer):
        serializer.save(owner=self.request.user)


class ClassBasedView(generics.ListCreateAPIView):
    serializer_class = FuelEffeciencySerializer
    permission_classes = (permissions.AllowAny,)

    def get_queryset(self):
        return FuelEffeciency.objects.all()

    def perform_create(self, serializer):
        serializer.save(owner=self.request.user)


class ClassBasedDetailView(generics.RetrieveUpdateDestroyAPIView):
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)
    serializer_class = FuelEffeciencySerializer

    def get_queryset(self):
        return FuelEffeciency.objects.all()


class BaseView(TemplateView):
    template_name = "milage/milage.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        db_pks = [i.id for i in FuelEffeciency.objects.all()]
        context["db_pk"] = db_pks

        description = [
            """This is cooler than it seems.""",
            """<a href=https://en.wikipedia.org/wiki/Representational_state_transfer>Rest frameworks</a> let you push data in and out of an appserver agnostic of the view.  An iPhone app, a Casio watch, and a Playstation4 can send and receive the same data from the server.  This page is just one view of the data, as html, xml, or json.  The display here is just to make it accessible to web browsers.""",
            """The top list and the botton grid just use different wires to connect to the SQL.  I like the bottom grid myself.""",
        ]
        context["description"] = description

        return context

mysite_project/templates/milage/milage.html
{% extends "base.html" %}
{% load static %}

{% block title %}Milage w/ DRF{% endblock title %}

{% block header %}Milage using Django Rest Framework (DRF){% endblock header %}

{% block loadjs %}
  {{ block.super }}
{% endblock loadjs %}

{% block content %}
<div id="app">
  <div class="container">
    <div class="row">
      <div class="col">
        <ul>
          <li><a href="{% url 'milage:class_based_drf' %}" class="sidebar-item">Class Based DRF</a></li>
          <ul>
            {% for item_pk in db_pk %}
              <li><a href="{% url 'milage:class_detail' item_pk %}" class="sidebar-item">Class Based Detail View DRF Item {{ item_pk }}</a></li>
            {% endfor item_pk %}
          </ul>
        </ul>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col">
        <ul>
          <li><a href="{% url 'milage:api-root' %}" class="side_bar_item">DRF API Root</a></li>
          <li><a href="{% url 'milage:FuelEffeciency-list' %}" class="sidebar-item">Fuel Effenciency Routing</a></li>
          <table class=table>
            <tr>
              <th>Item</th>
              <th>html view</th>
              <th>xml view</th>
              <th>json view</th>
            </tr>
            {% for item_pk in db_pk %}
              <tr>
                <td>{{ item_pk }}</td>
                <td><a href="{% url 'milage:FuelEffeciency-detail' item_pk %}" class="sidebar-item">html</a></td>
                <td><a href="{% url 'milage:FuelEffeciency-detail' item_pk 'xml' %}" class="sidebar-item">xml</a></td>
                <td><a href="{% url 'milage:FuelEffeciency-detail' item_pk 'json' %}" class="sidebar-item">json</a></td>
              </tr>
            {% endfor item_pk %}  
          </table>
        </ul>
        <li><a href="../api_auth/login/" class="sidebar-item">Authentication via DRF</a></li>
      </div>
    </div>
  </div>
</div>
{% endblock content %}