mysite_project/ajax_polls/urls.py
from django.urls import path

from . import views


app_name = "ajax_polls"
urlpatterns = [
    path("ajax_polls/", views.AjaxDetails.as_view(), name="ajax_polls"),
    path("", views.IndexView.as_view(), name="index"),
]

mysite_project/blog/urls.py
from django.urls import path
from . import views


app_name = "blog"
urlpatterns = [
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("", views.IndexView.as_view(), name="post_list"),
]

mysite_project/ajax_polls/views.py
from django.shortcuts import get_object_or_404
from django.views import generic
from django.utils import timezone
from django.http import JsonResponse

from polls.models import Question, Choice


class IndexView(generic.ListView):
    template_name = "ajax_polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by(
            "-pub_date"
        )[:5]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        description = [
            """Remember the Polls app?  This page does the same task, but uses Ajax instead.""",
            """Ajax is a kind of javascript that allows a webpage to send requests and accept responses without refreshing the entire page.""",
            """When you request the page at the url you see in your browser's location bar, Django does a plain vanilla html response.  The response has a bit of javascript, which attaches an ajax function to a click event.  Clicking a Question or Choice above activates that ajax function.""",
            """Here is the interesting part of ajax:  Activating the ajax functions sends a request to a different url from the one in the browser location bar.  You wire up the ajax url to hit a separate function in the appserver, which processes the ajax request and returns the response as json directly back to the requesting ajax.""",
            """""",
        ]
        context["description"] = description
        return context


class AjaxDetails(generic.TemplateView):
    template_name = "ajax_polls/index.html"
    model = Question

    def get(self, request, *args, **kwargs):
        if request.GET["function"] == "pull_choices":
            question_pk = request.GET["question_pk"]
            payload = {
                queryresponse.pk: {
                    "choice_pk": queryresponse.pk,
                    "choice_text": queryresponse.choice_text,
                }
                for queryresponse in Choice.objects.filter(question_id=question_pk)
            }
            return JsonResponse(payload)

    def post(self, request, *args, **kwargs):
        choice_pk = request.POST["choice_pk"]
        question_pk = request.POST["question_pk"]
        count = ajax_vote(question_pk, choice_pk)
        payload = {"count": count}
        return JsonResponse(payload)


def ajax_vote(question_pk, choice_pk):
    question = get_object_or_404(Question, pk=question_pk)
    try:
        selected_choice = question.choice_set.get(pk=choice_pk)
    except (KeyError, Choice.DoesNotExist):
        return False
    selected_choice.votes += 1
    selected_choice.save()
    return selected_choice.votes

mysite_project/templates/ajax_polls/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Ajax Polls{% endblock title %}
{% block header %}Polls with Ajax{% endblock header %}

{% block loadjs %}
  {{ block.super }}
  <script src="{% static 'ajax_polls/js/jquery-3.3.1.min.js' %}" type="text/javascript"></script>
{% endblock loadjs %}

{% block styles %}
  {{ block.super }}
  <link rel="stylesheet" type="text/css" href="{% static 'ajax_polls/css/style.css' %}" />
{% endblock styles %}

{% block content %}
  <nav aria-label='breadcrumb'>
    <ol class='breadcrumb'>
      <li class='breadcrumb-item active' aria-current='page'>Poll Index</li>
    </ol>
  </nav> 
  <div>
    {% if latest_question_list %}
      <ul class="list-group">
        {% for question in latest_question_list %}
          <li class="list-group-item">
            <div class="holder" ajax-function-url="{% url 'ajax_polls:ajax_polls' %}">
              <a name="{{ question.id }}" class="ajax-polls-item">{{ question.question_text }}</a>
            </div>
          </li>
        {% endfor %}
      </ul>
    {% else %}
      <p class="empty">No polls are available.</p>
    {% endif %}
  </div>
{% endblock content %}

{% block js %}
  {{ block.super }}
  <script src="{% static 'ajax_polls/js/ajax_poll_update.js' %}" type="text/javascript"></script>
{% endblock js %}